language: java
jdk:
- oraclejdk8
env:
  global:
    secure: WPbUMDVgvSMYexR/4z7uu9aUm74Qj8D6khnbuLAAD7BWEMHrU+nXQ2igFNGmnG31OCFBK+7fTtz/UHlTIyHG6ck2p0tieq2uBmg7nYQBdMx6vzOwZ2HC1teYRDvgot8MI4mL0tiGxhsA/xE0PxrVahMAaLNEmwnuzJqDbq4x+dG4RMpmHoNS27vRAFqKrKxcdkAKun+WBkwvdgVl6iwkjJDufvIyaPXI63iiP1QwwQ8EyBf8JrpytiO7hAXy6eCiUyDbRtm2t6xlVabcGO1Ds5OhTuV41C9X1m+bGoU9TAvnk3g7OZso2WeRwSWUnYC99TfPXjAFAEf894MGu73EJZ9kOhO8zuJmEifR9Nb2COTnX/TrIrk8mpgAdY+7owim06Tzd+deIVwtVHnrYl8zTH3+lYRh4UZQNbXiI15Vc/UzyczMNiepViVW5oj7fNTt7PJcObzhJMtYCF/kKTel4oOhPYxlTfE1+IchakNxc+P7PzQBNLYpNGHthN1q+joDBUOsfJG4sNTUaP5F0zYmQwR9udfgGHCdugz8iLZOcX0B7eC3ILDgrbiz1xirsBu1iGbrqLelx9kEq+oKQ37KVJM4RryObVpJekdRoFsj28urtEfUpRmE1u9dsuV0YnmhHSZpV1E+T1g71exyXAh3MVyLc9Lj1ezyHf4jCg2xGts=
addons:
  sonarcloud:
    organization: davidalonsobadia-github
    token:
      secure: "$SONAR_TOKEN"

script:
  - "./mvnw clean install -B"
  - "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
